### ISSUE TITLE
DialogJump.ahk 管理员身份运行时Ctrl+G无效

### ISSUE THREAD

**Issue by chunln** [Chaoses-Ib/IbDOpusScripts#1]
脚本`DialogJump.ahk` 中 `dopusrt := StrReplace(WinGetProcessPath("ahk_exe dopus.exe"), "dopus.exe", "dopusrt.exe")` 这句代码在管理员模式运行时不生效，导致功能无法正常使用，麻烦大佬看看。

**Comment by Chaoses-Ib** [comment]
可以复现，不过在我这边是由于 DOpus 的 bug 导致的。在用管理员权限运行时，DOpusRT 会在很长时间后才结束进程，造成 RunWait 堵塞。即使手动执行命令行也有同样的问题：
```cmd
"C:\Program Files\GPSoftware\Directory Opus\dopusrt.exe" /info %TEMP%\DOpus_pathlist.txt,paths
```

**Comment by Chaoses-Ib** [comment]
[已修复](https://github.com/Chaoses-Ib/IbDOpusScripts/blob/main/DialogJump.ahk)，请测试。

**Comment by chunln** [comment]
> [已修复](https://github.com/Chaoses-Ib/IbDOpusScripts/blob/main/DialogJump.ahk)，请测试。

大佬威武
