### ISSUE TITLE
数字转中文能不能不要单位

### ISSUE THREAD

**Issue by MyACGN** [Chaoses-Ib/IbDOpusScripts#4]
比如321转成三二一，而不是三百二十一

**Comment by Chaoses-Ib** [comment]
已添加 [阿拉伯数字转中文数字-无单位](https://github.com/Chaoses-Ib/IbDOpusScripts/blob/main/Rename%20Scripts/%E9%98%BF%E6%8B%89%E4%BC%AF%E6%95%B0%E5%AD%97%E8%BD%AC%E4%B8%AD%E6%96%87%E6%95%B0%E5%AD%97-%E6%97%A0%E5%8D%95%E4%BD%8D.js)。
